### PR TITLE
Cloudflare Migration

### LINKED ISSUE #217: Bandwidth usage
Looks we just went over the bandwidth limit for February by ~10 GB, which results in Netlify automatically billing us for a 100 GB add-on pack. Some questions:

1. Do we have any visibility on how bandwidth is being used, maybe through Sentry or some other source? The free tier does not include analytics unfortunately.
2. Should we look into putting the site (or maybe just media assets) behind Cloudflare / another CDN? The other option is to upgrade to Netlify Pro for $20/month but it seems kind of costly since we're still barely pushing any bandwidth.

### PR DESCRIPTION
**Pull request by aw-0**
Draft PR of the migration to Cloudflare Pages & Cloudflare email workers for forms

- [x] Redirects
- [x] Move frontend from Netlify Forms to custom event override
- [x] Setup email workers & handle event submission

closes #217

### CODE REVIEW

**Comment by aw-0** [comment]
All that really needs to be done is the email workers. After being built out, in order for me to test, we'd need to migrate email over from mailgun to cloudflare. There's [catch-all rules & email forwarding](https://developers.cloudflare.com/email-routing/), and [this Twitter thread (lol) on how to set up email sending via gmail](https://x.com/neilsuperduper/status/1732419669867245975?s=20) like have now

Also - an organization owner needs to [add the repository to Cloudflare Pages](https://dash.cloudflare.com/eb09a67d16effcedf18472e3926ce09d/workers-and-pages/create/pages) as well. Gh says I don't have the perms to that

**Comment by aw-0** [comment]
Need to test this when the Cloudflare emails are set up, but other than that it runs perfectly fine on Cloudflare! 

@Chaldron @JosephShepin any chance either of you could look into transferring from Mailgun when you're free? included some details in the prior comment :)

**Comment by Chaldron** [comment]
Sorry for the delayed response, was traveling out of the country :) I just added a new page to Cloudflare pointing to the main branch of this repo, and also started the process of migrating the domain from Netlify's DNS servers to Cloudflare's. Once that's done, I'll update the email rules and follow the links Andrew mentioned to setup the catch-all/forwarding rules and test if we can send/receive on the domain. Should we merge this change in now so the site works on Cloudflare from the main branch? 

Hopefully on Monday we'll be fully migrated :) Thanks again for all your guys' work on this!

**Comment by aw-0** [comment]
No problem! Hope you had a great trip. Really the only thing blocking this from being merged is configuring the form email to Cloudflare. I'm currently out of town until the middle of next week, so I could play around with it when I'm back.

Or we can merge without it 🤷‍♂️ doubt any forms will be submitted over the end of our spring break/the start of school

**Comment by Chaldron** [comment]
Thanks, and sorry about the email spam! Just want to make sure we can send/receive correctly and we're not silently missing anything. Otherwise, the site is now being served from Cloudflare Pages and the basic functionality seems to work so whenever we have the form submission working we can merge this. Thanks again so much for all your work on this!

**Comment by Chaldron** [comment]
By the way, I think it's best to leave Mailgun to handle the sending side, so the existing configuration we all have (smtp.mailgun.org etc) should continue to work. On the receiving side, I just made a small catch-all worker that forwards all incoming email to our personal addresses.

**Comment by JosephShepin** [comment]
Hosting on cloudflare pages looks amazing!

**Comment by Chaldron** [comment]
Ah gotcha, I misunderstood how form submission would work with Cloudflare. I thought Cloudflare would provide some way to submit the form from an email they control which would just need to be received at a @stevenson.space domain. If we need to use the Mailgun API anyway then I think we could just leave both sending and receiving to Mailgun since it has worked pretty well in the past. I'll make an API key for you and send it over on Gitter. Thanks for working on this!

**Comment by aw-0** [comment]
🎉 Merged! Thanks for all the help Aditya

Curious, looks like we had auto build setup daily (for events page I assume?) - how is that being managed? Deploy hooks exist for CF Pages - put the specific url in Gitter. Wonder if you could take a look @Chaldron and edit your cron job/whatever you have setup when free :)
Arc Screenshot 2024-04-02 at 22 41 52@2x

**Comment by Chaldron** [comment]
Sorry just got around to this, I have setup a GitHub action that runs nightly to call the deploy hook. I'll keep an eye on it over the next week to make sure it's working as expected.

**Pull request merged**
