### PR TITLE
Update lunch

### PR DESCRIPTION
**Pull request by aw-0**
New month - new lunch menu!

### CODE REVIEW

**Comment by JosephShepin** [comment]
@aw-0 should we wait until dec 1 to merge this in?

**Comment by aw-0** [comment]
@JosephShepin I was also going to wait for the 1st as well - showed up to school today and heard all around that the menu wasn't showing up. So pushed the update to today to get that fixed - probably due to a weird edge case where week 4 became week 1 because last week messed the schedule up.

**Comment by JosephShepin** [comment]
so we should merge now?

**Comment by aw-0** [comment]
Yep that would be great

**Comment by JosephShepin** [comment]
Thanks!

**Pull request merged**
