### PR TITLE
Vue 3

### PR DESCRIPTION
**Pull request by JosephShepin**
- [x] vuex -> pinia
- [x] fix dropdowns 
- [x] rewrite the google auth using fetch() instead of axios (not a requirement, but will allow us to get rid of axios)
- [x] confirm request documents form submission on netlify still works

- v-model was changed a bit. It now uses the variable name `modelValue` instead of `value`
- rewrote the transfer settings feature using the fetch() api
- switch to GA 4 (UA is being terminated in July 2023)
- querystring-es3 be added in addition to the regular version as the package has some support issues with webpack versions 5+. 
- I had to remove vue-hammer as it doesn't support vue3. Everywhere where there was a tap event, I just made it an @click. I'm not sure if this breaking anything yet as I have yet to test this extensively on mobile. There were some swipe events that were removed and have not been replaced.
- Added Sentry for error monitoring. We can get rid of this later if the number of errors goes to a negligible level - It's really easy to turn on and off. 
- Replaced VueX with pinia. Pinia is the new version of vueX and enforces typescript, and allows us to easily break up our stores into separate categories, instead of having all the different stores in one file.

### CODE REVIEW

**Comment by JosephShepin** [comment]
- [ ] QR Codes
- [ ] Squash small commits 
- [ ] Sentry

**Comment by JosephShepin** [comment]
I still have to figure out how to get the QR codes page working with vue3. The package I was using doesn't work with vue3, and all the vue3 compatible ones I found either don't work or don't have good features. 

The most janky part that I'm not that proud of is the StaggerAnimation component. I will try to revisit that soon and make it better.

**Comment by Chaldron** [comment]
Wow, this looks like a lot of work! I clicked around the deploy preview of this branch and tested out some of the features and everything appears to be working right now. I guess you can just monitor Sentry for a while once this actually rolls out and see if there are more edge cases that weren't covered. Thanks a lot for working on this migration, like I mentioned I gave up on this after seeing how much work it was but this is definitely the right move.

**Comment by JosephShepin** [comment]
Update on QR Codes: The `vue3-qr-code-styling` is the vue3 version of the QR codes that I will implement soon. 
I eliminates the "Download" button, and renders it as an image, allowing it to be saved directly on all browsers and devices.

**Comment by JosephShepin** [comment]
@Chaldron @abhinavpappu @aw-0 I think i'm finished with the vue2 -> vue3 conversion. I think we should try to get this rolled out soon. Thanks!

**Comment by aw-0** [comment]
🎉 That's awesome - really appreciate your work! This'll make maintainability a ton easier. I'll poke around with it later today and see if I can get custom links ported over correctly :)

**Comment by abhinavpappu** [comment]
Wow this is massive and looks amazing, thanks for doing all of it! I looked over it at a high level and seems fine. I'll see if I get time to look at some things in more detail soon, but go ahead and merge it 🎉, and using sentry to monitor for issues is a great idea (testing in production for the win 😄)!

The vue-hammer replacement to @click is fine, I just used vue-hammer since it made tapping things an ever so slightly nicer experience on mobile, but shouldn't have any impact on functionality.

**Comment by Chaldron** [comment]
Wow, excellent work! Cannot even begin to imagine the effort required to pull this off without breaking a billion things. Super glad you were able to figure it out where I couldn't! :P

**Pull request merged**
