### PR TITLE
Add English Section Amstud Books

### PR DESCRIPTION
**Pull request by Aaaaa501**

### CODE REVIEW

**Comment by JosephShepin** [comment]
@Aaaaa501 thanks for submitting your first PR! 

We will have to move those documents over to our Mega account. 

They say as I say: https://mega.nz/file/YMVEFaYQ#pl400jzTELaXek2Q5FHwqL50_kEBLFbm3A9Zu1FfhyY

The crucible: https://mega.nz/file/gc8RWJKL#QvsabwgSfaOOTapJ_U5qWyUF4URxnR8Ub3c2eXIXxUY

Homegoing: https://mega.nz/file/5IVVjBKK#pqL7HTIvLnYJpuV-DfNrQw7aPpFEn5G-5SNhQwxKSpM

**Review by JosephShepin — CHANGES_REQUESTED** [review]
check pr

**Comment by JosephShepin** [comment]
Screenshot 2022-12-03 at 10 12 03 PM
1. Can these be put under the existing AMSTUD category?
2. Do you know if the books marked old? are not used anymore? If so we can remove them.

**Comment by JosephShepin** [comment]
syntax error

**Comment by JosephShepin** [comment]
Please run your code locally to find these issues, if you need help please let me know - It's not safe to be committing code that hasn't been tested locally. There is still a missing comma.

**Comment by Aaaaa501** [comment]
Sorry I didnt anticipate i'd make so many typos. I keep seeing this issue when I try to run "npm run serve" or "npm run-script serve", and it dosent happen in other projects. I've even tried "npm run serve" in a project I just made with vue-create, its just in this project. Do you know why?

Screen Shot 2022-12-04 at 7 45 35 PM

**Review by JosephShepin — APPROVED** [review]

**Comment by JosephShepin** [comment]
@Aaaaa501 congrats on your first PR 🥳 !!!

**Pull request merged**
