### PR TITLE
Refactor to Vite

### PR DESCRIPTION
**Pull request by aw-0**
Replaces vue-cli with Vite, Vue's new build tool

Breaking Changes:
- Enviornment variables have been renamed to start with `VITE_` instead of `VUE_APP_`
- `npm run serve` -> `npm run dev`
- `require()` no longer works with Vite, and images can no longer be imported in-line. They must be imported like any other module, or referenced directly (e.x. `src="@/assets/...`)

SS now builds in 3 seconds, instead of 8! And with almost instant (~100ms) dev server startups as well

### CODE REVIEW

**Comment by aw-0** [comment]
Also looks like it shaved 8 seconds off our build time too 👀

**Comment by JosephShepin** [comment]
Screenshot 2022-12-31 at 9 02 59 AM
looks good, to solve the snow issue you can make this little chance - move the images returned out of the icons object.

**Comment by aw-0** [comment]
🤦‍♂️ thanks for pointing that out

**Comment by aw-0** [comment]
@JosephShepin any ETA on when we could get this merged? Want to port music over to Vite and hopefully get it finished over this week

**Comment by JosephShepin** [comment]
> @JosephShepin any ETA on when we could get this merged? Want to port music over to Vite and hopefully get it finished over this week
Screenshot 2023-01-04 at 10 56 51 AM

**Comment by aw-0** [comment]
No worries! Just hadn't heard any updates and wanted to follow up :)

**Comment by JosephShepin** [comment]
@aw-0 can you see about the google auth working in prod with the wrong variable name? it's the last sentence in that SS.

**Comment by aw-0** [comment]
Yeah it seems to work fine @JosephShepin - pretty odd. Even tried it in an incognito tab and still worked

**Comment by aw-0** [comment]
Although, it doesn't seem to be working in the deploy preview. And when I try it locally, auth is bypassed all together eve though I can't seem to find any evidence of why that is happening. Pretty odd

Also - was reading through `Login.vue` and noticed that the `state` param of the OAuth client is used incorrectly. Right now it stores the destination of the users, but it should *actually* be storing a random string that we check after the Google redirect to prevent CSRF. Auth0 has a good article on that [here](https://auth0.com/docs/secure/attack-protection/state-parameters)

More than happy to fix this in this PR or a separate one. It isn't a crazy critical bug but still one we should fix soon

**Pull request merged**
