### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by JosephShepin**
blocked by #210

### CODE REVIEW

**Comment by JosephShepin** [comment]
Screenshot 2023-12-28 at 1 42 14 PM
@Chaldron for some reason we can't see deploy logs so i'm not sure why this is failing. Thanks!

**Comment by aw-0** [comment]
Just cloned this and can't replicate the build fail on my end - odd

**Comment by Chaldron** [comment]
Here's the log from Netlify, I re-ran the build again and it produced the same error:

```
.. package installation ..
4:46:03 PM: added 432 packages in 6.686s
4:46:03 PM: > stevenson-space@0.1.0 prebuild /opt/build/repo
4:46:03 PM: > node scrapers/events.js
4:46:03 PM: Events saved.
4:46:03 PM: > stevenson-space@0.1.0 build /opt/build/repo
4:46:03 PM: > vite build
4:46:03 PM: (node:4223) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token "??="
4:46:03 PM:     at Loader.moduleStrategy (internal/modules/esm/translators.js:149:18)
4:46:03 PM: (Use `node --trace-warnings ...` to show where the warning was created)
4:46:03 PM: (node:4223) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
4:46:03 PM: (node:4223) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
4:46:03 PM: ​
4:46:03 PM: (build.command completed in 7.5s)
4:46:03 PM: ​
4:46:04 PM: Finished processing build request in 34.647s
```

Could be related to the dependency upgrades?

**Comment by Chaldron** [comment]
Looks like that worked, some warnings:

```
5:11:26 PM: > vite build
5:11:26 PM: The CJS build of Vite"s Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vite v5.0.10 building for production...
5:11:26 PM: transforming...
5:11:29 PM: ✓ 417 modules transformed.
5:11:30 PM: rendering chunks...
5:11:30 PM: warnings when minifying css:
5:11:30 PM: ▲ [WARNING] Comments in CSS use "/* ... */" instead of "//" [js-comment-in-css]
5:11:30 PM:     <stdin>:128:16:
5:11:30 PM:       128 │   --num-rows: 5 // changed through JavaScript to 5 or 6 depending...
5:11:30 PM:           ╵                 ~~
5:11:30 PM: 
5:11:30 PM: warnings when minifying css:
5:11:30 PM: ▲ [WARNING] "padding-botton" is not a known CSS property [unsupported-css-property]
5:11:30 PM:     <stdin>:484:2:
5:11:30 PM:       484 │   padding-botton: 20px;
5:11:30 PM:           │   ~~~~~~~~~~~~~~
5:11:30 PM:           ╵   padding-bottom
5:11:30 PM:   Did you mean "padding-bottom" instead?
5:11:30 PM: 
5:11:30 PM: warnings when minifying css:
5:11:30 PM: ▲ [WARNING] "positon" is not a known CSS property [unsupported-css-property]
5:11:30 PM:     <stdin>:82:2:
5:11:30 PM:       82 │   positon: absolute;
5:11:30 PM:          │   ~~~~~~~
5:11:30 PM:          ╵   position
5:11:30 PM:   Did you mean "position" instead?
5:11:30 PM: 
```

**Pull request merged**
